version: 2.1
jobs:
 build:
   machine: true
   steps:
     ## install more recent version of docker-compose
     - run: sudo curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
     - run: sudo chmod a+x /usr/local/bin/docker-compose

     - checkout

     # buildroot
     - run: cd ./docker__buildroot && docker-compose up

     # yocto
     - run: cd ./docker__yocto && docker build --no-cache --build-arg USER=$USER -t rubuschl/de1soc-yocto:456 .
     - run: cd ./docker__yocto && docker run --rm -ti --user=$USER:$USER -v $PWD/output:/home/$USER/poky/build --workdir=/home/$USER rubuschl/de1soc-yocto:456
