version: 2.1
jobs:
    build_buildroot:
        machine: true
        steps:
        ## install more recent version of docker-compose
          - run: sudo curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          - run: sudo chmod a+x /usr/local/bin/docker-compose

          - checkout

        ## buildroot
          - run: cd ./docker__buildroot && docker-compose up --exit-code-from de1soc_buildroot


    build_yocto:
        machine: true
        steps:
        ## install more recent version of docker-compose
          - run: sudo curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          - run: sudo chmod a+x /usr/local/bin/docker-compose

        ## yocto (just fetch, due to timeout in ci infrastructure)
          - checkout
          - run: cd ./docker__yocto && docker-compose -f ./docker-compose.yml run --rm de1soc_yocto /usr/local/bin/build.sh --runall=fetch

## parallelization
workflows:
    version: 2
    build:
        jobs:
          - build_buildroot
          - build_yocto

